### ISSUE TITLE
Allow lookup with zipcode only

### ISSUE THREAD

**Issue by avh4** [mchat/call-my-congress#1]
Some people may be hesitant (and rightly so) to enter their address.  Providing an address should be optional.

Possible data sources for zip -> congressional district lookup
  - https://sunlightlabs.github.io/congress/districts.html
  - http://whoismyrepresentative.com/api (district number is in the entry for the house representative) http://whoismyrepresentative.com/getall_mems.php?zip=10001&output=json

**Comment by mchat** [comment]
The whoismyrepresentative.com API is no longer functional, which means that I've had to remove this functionality (see #27). I'd like to find a replacement API to be able to provide this feature again in the future, but don't have much time at the moment to investigate myself. PRs are very welcome though!
