### ISSUE TITLE
DC Addresses Not Accepted

### ISSUE THREAD

**Issue by alidavis74** [mchat/call-my-congress#21]
I received the following "Provided URL does not map to a valid state and district number." when I looked up my (non-voting) representative from the District of Columbia. Please ensure that all Americans are able to use this to find their representatives, voting or not.

**Comment by mchat** [comment]
@alidavis74 thank you for reporting this bug! It looks like I wasn't properly handling any non-voting delegate districts. I just made a fix, and so if you try your address again shortly you should see your representative as expected. You can see more details about this fix here: #23
