### ISSUE TITLE
Nodemon in restart loop

### ISSUE THREAD

**Issue by melismae** [mchat/call-my-congress#22]
Hi there! I just forked your repo and ran locally yesterday. I ran into issues with starting the backend before the frontend - nodemon just ends up in this restart loop then errors out. Starting the frontend before backend is fine, tho Nodemon seems to restart more with changes than it should. It looks like adding ignore flags on line 16 of the package.json start script helps this
```
    "backend": "PORT=3000 nodemon backend/app/server.js --ignore tmp/ --ignore app/",
```
Let me know if you see this on your end too - I'm happy to put in a PR.

**Comment by mchat** [comment]
Hey @melismae! Thank you for looking into this. I was able to repro the issue locally, and confirmed that your proposed changes did resolve the bug for me too. Feel free to open a PR with your change and I'll approve it!

**Comment by mchat** [comment]
One caveat: it looks like you may want to only ignore the top-level directories: `--ignore ./tmp/ --ignore ./app/`. Otherwise, nodemon ignores `backend/app/` as well, and does not restart when changes to the server code are made.
